# Generated by Django 2.2.19 on 2022-04-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20220414_2032'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='unique_authors_recipe'),
        ),
    ]
